[package]
name = "grpc-mesh"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.12.6"
tokio = { version = "1", features = ["full"] }
tonic = "0.11.0"
tonic-reflection = "0.11.0"
tonic-web = "0.11.0"

[build-dependencies]
tonic-build = "0.11.0"
